%YAML 1.0
---

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

Camera.topic_left: /cam0/image_raw
Camera.topic_right: /cam1/image_raw

Camera.model_left: fisheye
Camera.model_right: fisheye

Camera.left_nwidth: 1024
Camera.left_nheight: 768

Camera.right_nwidth: 1024
Camera.right_nheight: 768

# Camera calibration and distortion parameters (OpenCV) 
Camera.fxl: 545.7402000594014
Camera.fyl: 516.7898455908171
Camera.cxl: 546.4624873938807
Camera.cyl: 399.68834148863493

Camera.k1l: -0.06983837053126551
Camera.k2l: 0.030679193251357234
Camera.p1l: -0.029318268716673087
Camera.p2l: 0.008383563478792275

Camera.fxr: 543.6000821015224
Camera.fyr: 524.280213672173
Camera.cxr: 544.4238023037506
Camera.cyr: 381.4178892040695

Camera.k1r: -0.059680378064520846
Camera.k2r: 0.01009738651194745
Camera.p1r: -0.01025701371639368
Camera.p2r: 0.002248862281197446

# distortion_model: equidistant

# Camera Extrinsic parameters T_b_ci ( v_b = T_b_ci * v_ci )
body_T_cam0: 
   rows: 4
   cols: 4
   dt: d
   data: [-0.99991936,-0.00798246, 0.00987736, 0.04642638,
        0.00780874, -0.99981631, -0.01750317,  0.11439388,
        0.01001526, -0.01742462,  0.99979802, -0.00785582,
        0., 0., 0., 1.]

body_T_cam1:
   rows: 4
   cols: 4
   dt: d
   data: [-0.99987241, -0.0061818,   0.01472889, -0.07196744,
         0.00589771, -0.99979723, -0.01925389,  0.11590179,
         0.01484493, -0.01916456,  0.99970613, -0.00538312,
         0., 0., 0., 1.]

# body_T_cam0: 
#    rows: 4
#    cols: 4
#    dt: d
#    data: [0.99998651, 0.00182615, 0.0048626, -0.11842431,
#         -0.0018178,  0.99999686, -0.00172214, 0.00082311,
#         -0.00486573, 0.00171327, 0.99998669, -0.00069913,
#         0., 0., 0., 1.]

# body_T_cam1:
#    rows: 4
#    cols: 4
#    dt: d
#    data: [1., 0., 0., 0.,
#           0., 1., 0., 0.,
#           0., 0., 1., 0.,
#            0., 0., 0., 1.]

#--------------------------------------------------------------------------------------------
# SLAM Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
debug: 0
log_timings: 0

mono: 0
stereo: 1

force_realtime: 1

# Estimator Mode
slam_mode: 1

# Loop Closing mode
buse_loop_closer: 1

# Stereo rectify or not
bdo_stereo_rect: 0
alpha: 0.

# Undist Image or not
bdo_undist: 1

# Init / KF px th.
finit_parallax: 20.

# Features Extractor
use_shi_tomasi: 0
use_fast: 0
use_brief: 1
use_singlescale_detector: 1

# Min dist between kps (define the number of kps)
nmaxdist: 35

# Features quality th.
nfast_th: 10
dmaxquality: 0.001 # used for gftt or singlescale

# Pre-processing
use_clahe: 1
fclahe_val: 3

# KLT related settings.
do_klt: 1
klt_use_prior: 1
btrack_keyframetoframe: 0
nklt_win_size: 9
nklt_pyr_lvl: 3

# Opencv Default: 30 iters. + 0.01 prec.
nmax_iter: 30
fmax_px_precision: 0.01

fmax_fbklt_dist: 0.5
nklt_err: 30.

# Matching th.
bdo_track_localmap: 1

fmax_desc_dist: 0.2 #0.35 # Ratio from desc size (for binary desc.) 
fmax_proj_pxdist: 2.

# Randomize RANSAC?
doepipolar: 1
dop3p : 0
bdo_random: 1
nransac_iter: 100
fransac_err: 3.

# Reproj err th.
fmax_reproj_err: 3.
buse_inv_depth: 1

# Ceres related parameters
robust_mono_th: 5.9915 # (20% : 3.2189 / 10% :  4.6052 / 5% : 5.9915 / 2%: 7.8240 / 1%: 9.2103)  

use_sparse_schur: 1
use_dogleg: 0
use_subspace_dogleg: 0
use_nonmonotic_step: 0

# Estimator parameters
apply_l2_after_robust: 1

nmin_covscore: 25 # Min co-obs for optimizing in SLAM mode BA

# Map Filtering
fkf_filtering_ratio: 0.95

# Final Pass
do_full_ba: 0