%YAML:1.0
---
# Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 707.0912
Camera1.fy: 707.0912
Camera1.cx: 601.8873
Camera1.cy: 183.1104

Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0

Camera2.fx: 707.0912
Camera2.fy: 707.0912
Camera2.cx: 601.8873
Camera2.cy: 183.1104

Camera2.k1: 0.0
Camera2.k2: 0.0
Camera2.p1: 0.0
Camera2.p2: 0.0

Camera.width: 1226
Camera.height: 370

Camera.Base.Line: 379.8145
Camera.NeedUndistortion: 0
Camera.fps: 10

Map.ActiveMap.Size: 12

# valid feature numbers to decide the tracking / init status
numFeatures.initGood: 100
numFeatures.trackingGood: 50
numFeatures.trackingBad: 10
# ORB Extractor: Number of features when initalizing
ORBextractor.nInitFeatures: 300
# ORB Extractor: Number of new features to detect when needs to create a new KF
ORBextractor.nNewFeatures: 100
# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2
# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8
# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

Min.Init.Landmark.Num: 200

View.ORB.Extractor.Result: 0
View.LK.Folw: 0
Viewer.ViewpointX: 0
Viewer.ViewpointY: 1000 # The distance of the Y axis from the origin
Viewer.ViewpointZ: 0
Viewer.Camera.Focus: 5000 # The larger the focal length, the less content can be displayed on the screen, and the displayed content will appear larger
View.Axis.Direction: 6 # AxisX: 2; AxisY: 4; AxisZ: 6

DBOW2.VOC.Path: "/home/fu/VSLAM_ws/src/config_pkg/voc/ORBvoc.txt"

Backend.Open: 1
Trajectory.Save.Path: "/home/fu/VSLAM_ws/res.txt"

Loop.Closing.Open: 1
Loop.Show.Closing.Result: 1
Loop.Threshold.Heigher: 0.027
Loop.Threshold.Lower: 0.02
Loop.Closig.Keyframe.Database.Min.Size: 50
Pyramid.Level: 8